// +build !8x8

package board

const (
	BOARD_LEN  = 6
	BOARD_REAL = BOARD_LEN + 2

	INIT_WHITE1X, INIT_WHITE1Y = 2, 2
	INIT_WHITE2X, INIT_WHITE2Y = 3, 3
	INIT_BLACK1X, INIT_BLACK1Y = 2, 3
	INIT_BLACK2X, INIT_BLACK2Y = 3, 2
)
