// +build 8x8

package board

const (
	BOARD_LEN  = 8
	BOARD_REAL = BOARD_LEN + 2

	INIT_WHITE1X, INIT_WHITE1Y = 3, 3
	INIT_WHITE2X, INIT_WHITE2Y = 4, 4
	INIT_BLACK1X, INIT_BLACK1Y = 3, 4
	INIT_BLACK2X, INIT_BLACK2Y = 4, 3
)
